Repository seunghui-park/digital-hanaro-vanillaJS-clone, pull requests merged in 2025-04, with the labels that each got.

#6 [#3] fix: tailwind CSS 사용을 위한 디렉토리 구조 수정
  assets/css/event.css
  assets/css/home.css
  assets/css/region.css
  assets/css/style.css
  pages/home.html
  scripts/home.js
Labels: refactor

#9 [#1] feat: 홈 화면 생성
  assets/images/home/home_1.png
  assets/images/home/home_2.png
  assets/images/home/home_3.png
  assets/images/home/home_4.png
  index.html
  scripts/home.js
Labels: enhancement

#14 [#10] feat: footer 제작
  assets/images/footer/ico_sns1.png
  assets/images/footer/ico_sns2.png
  assets/images/footer/ico_sns3.png
  assets/images/footer/ico_sns4.png
  assets/images/footer/ico_sns5.png
  assets/images/footer/ico_sns7.png
  assets/images/footer/ico_sns9.png
  components/footer.html
  index.html
  pages/event.html
  pages/region.html
  scripts/common.js
Labels: enhancement

#26 [#25] feat: pre, next 버튼 추가 및 슬라이더 리팩토링
  index.html
  scripts/home.js
Labels: enhancement, refactor

#28 [#27] feat: footer hover 색상 추가
  assets/images/footer/ico_sns1_1.png
  assets/images/footer/ico_sns2_1.png
  assets/images/footer/ico_sns3_1.png
  assets/images/footer/ico_sns4.png
  assets/images/footer/ico_sns4_1.png
  assets/images/footer/ico_sns5_1.png
  assets/images/footer/ico_sns7_1.png
  assets/images/footer/ico_sns9_1.png
  components/footer.html
  scripts/common.js
Labels: enhancement
